In [1]:
import pandas as pd

In [5]:
path = r"C:\Users\JOKER\Desktop\berlin\Fächer\Summer School\Power Markets\Data"
slp = pd.read_csv(f"{path}/slp_profiles.csv")
slp

,timestamp_utc,timestamp_local,hb_normalized_kwh,gb_normalized_kwh,lb_normalized_kwh
0,2023-12-31T23:00:00Z,2024-01-01T00:00:00+01:00,27.110,15.705,17.028
1,2023-12-31T23:15:00Z,2024-01-01T00:15:00+01:00,25.127,15.158,16.454
2,2023-12-31T23:30:00Z,2024-01-01T00:30:00+01:00,23.237,14.636,16.030
3,2023-12-31T23:45:00Z,2024-01-01T00:45:00+01:00,21.409,14.164,15.706
4,2024-01-01T00:00:00Z,2024-01-01T01:00:00+01:00,19.643,13.741,15.482
...,...,...,...,...,...
35131,2024-12-31T21:45:00Z,2024-12-31T22:45:00+01:00,37.141,18.340,22.162
35132,2024-12-31T22:00:00Z,2024-12-31T23:00:00+01:00,35.633,17.818,20.941
35133,2024-12-31T22:15:00Z,2024-12-31T23:15:00+01:00,33.747,17.321,19.769
35134,2024-12-31T22:30:00Z,2024-12-31T23:30:00+01:00,31.674,16.799,18.697
35135,2024-12-31T22:45:00Z,2024-12-31T23:45:00+01:00,29.568,16.252,17.775

In [3]:
E_hb = 10000 * 3.5
E_gb = 200 * 30.0
E_lb = 20 * 100.0

In [4]:
forecast = pd.DataFrame()
forecast["timestamp_utc"] = slp["timestamp_utc"]
forecast["timestamp_local"] = slp["timestamp_local"]
forecast["hb_forecast_mwh"] = E_hb * slp["hb_normalized_kwh"] / slp["hb_normalized_kwh"].sum()
forecast["gb_forecast_mwh"] = E_gb * slp["gb_normalized_kwh"] / slp["gb_normalized_kwh"].sum()
forecast["lb_forecast_mwh"] = E_lb * slp["lb_normalized_kwh"] / slp["lb_normalized_kwh"].sum()
forecast

,timestamp_utc,timestamp_local,hb_forecast_mwh,gb_forecast_mwh,lb_forecast_mwh
0,2023-12-31T23:00:00Z,2024-01-01T00:00:00+01:00,0.948850,0.094230,0.034056
1,2023-12-31T23:15:00Z,2024-01-01T00:15:00+01:00,0.879445,0.090948,0.032908
2,2023-12-31T23:30:00Z,2024-01-01T00:30:00+01:00,0.813295,0.087816,0.032060
3,2023-12-31T23:45:00Z,2024-01-01T00:45:00+01:00,0.749315,0.084984,0.031412
4,2024-01-01T00:00:00Z,2024-01-01T01:00:00+01:00,0.687505,0.082446,0.030964
...,...,...,...,...,...
35131,2024-12-31T21:45:00Z,2024-12-31T22:45:00+01:00,1.299935,0.110040,0.044324
35132,2024-12-31T22:00:00Z,2024-12-31T23:00:00+01:00,1.247155,0.106908,0.041882
35133,2024-12-31T22:15:00Z,2024-12-31T23:15:00+01:00,1.181145,0.103926,0.039538
35134,2024-12-31T22:30:00Z,2024-12-31T23:30:00+01:00,1.108590,0.100794,0.037394
35135,2024-12-31T22:45:00Z,2024-12-31T23:45:00+01:00,1.034880,0.097512,0.035550

In [6]:
forecast["total_forecast_mwh"] = (forecast["hb_forecast_mwh"] + forecast["gb_forecast_mwh"] + forecast["lb_forecast_mwh"])
forecast

,timestamp_utc,timestamp_local,hb_forecast_mwh,gb_forecast_mwh,lb_forecast_mwh,total_forecast_mwh
0,2023-12-31T23:00:00Z,2024-01-01T00:00:00+01:00,0.948850,0.094230,0.034056,1.077136
1,2023-12-31T23:15:00Z,2024-01-01T00:15:00+01:00,0.879445,0.090948,0.032908,1.003301
2,2023-12-31T23:30:00Z,2024-01-01T00:30:00+01:00,0.813295,0.087816,0.032060,0.933171
3,2023-12-31T23:45:00Z,2024-01-01T00:45:00+01:00,0.749315,0.084984,0.031412,0.865711
4,2024-01-01T00:00:00Z,2024-01-01T01:00:00+01:00,0.687505,0.082446,0.030964,0.800915
...,...,...,...,...,...,...
35131,2024-12-31T21:45:00Z,2024-12-31T22:45:00+01:00,1.299935,0.110040,0.044324,1.454299
35132,2024-12-31T22:00:00Z,2024-12-31T23:00:00+01:00,1.247155,0.106908,0.041882,1.395945
35133,2024-12-31T22:15:00Z,2024-12-31T23:15:00+01:00,1.181145,0.103926,0.039538,1.324609
35134,2024-12-31T22:30:00Z,2024-12-31T23:30:00+01:00,1.108590,0.100794,0.037394,1.246778
35135,2024-12-31T22:45:00Z,2024-12-31T23:45:00+01:00,1.034880,0.097512,0.035550,1.167942

In [8]:
print("Quarter-hours:", len(forecast))
print("HB annual MWh: expected", E_hb, "scaled", forecast["hb_forecast_mwh"].sum())
print("GB annual MWh: expected", E_gb, "scaled", forecast["gb_forecast_mwh"].sum())
print("LB annual MWh: expected", E_lb, "scaled", forecast["lb_forecast_mwh"].sum())
print("Total annual MWh: expected", E_hb + E_gb + E_lb, "scaled", forecast["total_forecast_mwh"].sum())

Quarter-hours: 35136
HB annual MWh: expected 35000.0 scaled 35000.0
GB annual MWh: expected 6000.0 scaled 6000.0
LB annual MWh: expected 2000.0 scaled 1999.9999999999998
Total annual MWh: expected 43000.0 scaled 43000.0

A quarter-hour holds 0.25 hours, so average MW = MWh / 0.25

In [9]:
print("Average portfolio MW:", forecast["total_forecast_mwh"].mean() / 0.25)
print("Maximum quarter-hourly MWh:", forecast["total_forecast_mwh"].max())
print("Maximum average MW:", forecast["total_forecast_mwh"].max() / 0.25)

Average portfolio MW: 4.895264116575592
Maximum quarter-hourly MWh: 2.599625
Maximum average MW: 10.3985

In [10]:
forecast

,timestamp_utc,timestamp_local,hb_forecast_mwh,gb_forecast_mwh,lb_forecast_mwh,total_forecast_mwh
0,2023-12-31T23:00:00Z,2024-01-01T00:00:00+01:00,0.948850,0.094230,0.034056,1.077136
1,2023-12-31T23:15:00Z,2024-01-01T00:15:00+01:00,0.879445,0.090948,0.032908,1.003301
2,2023-12-31T23:30:00Z,2024-01-01T00:30:00+01:00,0.813295,0.087816,0.032060,0.933171
3,2023-12-31T23:45:00Z,2024-01-01T00:45:00+01:00,0.749315,0.084984,0.031412,0.865711
4,2024-01-01T00:00:00Z,2024-01-01T01:00:00+01:00,0.687505,0.082446,0.030964,0.800915
...,...,...,...,...,...,...
35131,2024-12-31T21:45:00Z,2024-12-31T22:45:00+01:00,1.299935,0.110040,0.044324,1.454299
35132,2024-12-31T22:00:00Z,2024-12-31T23:00:00+01:00,1.247155,0.106908,0.041882,1.395945
35133,2024-12-31T22:15:00Z,2024-12-31T23:15:00+01:00,1.181145,0.103926,0.039538,1.324609
35134,2024-12-31T22:30:00Z,2024-12-31T23:30:00+01:00,1.108590,0.100794,0.037394,1.246778
35135,2024-12-31T22:45:00Z,2024-12-31T23:45:00+01:00,1.034880,0.097512,0.035550,1.167942

In [11]:
forecast.to_csv(f"{path}/forecast_load.csv", index=False)